apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      name: user-management
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: jcortave/user-management
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: user-management
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: db_port
                  name: user-management
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: user-management
