spring:
  profiles:
    active: @activeProfile@
  application:
    name: notification

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key