server:
  port: ${PORT:7003}

spring:
  datasource:
    url: jdbc:${DB_PROVIDER:postgresql}://${DB_HOST:localhost}:${DB_PORT:5400}/${DB_DATABASE:notification}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin1234}
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  rabbitmq:
    addresses: rabbitmq
  zipkin:
    base-url: ${ZIPKIN_URL:http://zipkin}


logging:
  level:
    org.hibernate.SQL: debug
  file:
    path: /app/logs

