apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      dnsConfig:
        nameservers:
          - 8.8.8.8
      containers:
        - name: notification
          image: jcortave/notification
          imagePullPolicy: Always
          ports:
            - containerPort: 9003
            - containerPort: 587
            - containerPort: 25
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: notification
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: db_port
                  name: notification
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: notification
